// ★君のGASのURLを貼り付けてね！
export const GAS_URL = "https://script.google.com/macros/s/AKfycby-dUq_dfcitTMzpl8GPbyoQZUB9DGYEJyd7tZfxb9ToAs3XwMkgLRc7V64VlrsUrwo/exec";

// ★StripeのPayment LinkのURLを貼り付けてね！（Stripeアカウント作成後に設定）
export const STRIPE_PAYMENT_URL = "";

// 試験範囲モードで表示する一般的な時代区分名（タブの文学的な名前とは別）
export const ERA_DISPLAY_NAMES = {
    "china_five_hu":                  "五胡十六国時代",
    "china_ancient_china":            "中国古代（秦・漢）",
    "china_medieval_china":           "中国中世（唐・宋・元・モンゴル）",
    "china_early_modern_china":       "中国近世（明・清）",
    "mideast_ancient_orient":         "オリエント・メソポタミア",
    "mideast_islamic_expansion":      "イスラーム拡大期",
    "mideast_turco_mongol":           "オスマン帝国時代",
    "mideast_modern_turkey":          "近代中東・トルコ革命",
    "africa_african_kingdoms":        "アフリカ王国時代",
    "africa_scramble_for_africa":     "アフリカ分割",
    "europe_germanic":                "ゲルマン民族移動・フランク王国",
    "europe_ancient":                 "古代ギリシア・ローマ",
    "europe_medieval":                "中世ヨーロッパ・十字軍",
    "europe_modern":                  "絶対王政・市民革命",
    "europe_age_of_exploration":      "大航海時代",
    "europe_russia":                  "帝政ロシア",
    "europe_napoleon":                "ナポレオン時代",
    "europe_britain":                 "大英帝国（19世紀）",
    "india_indus":                    "インダス文明",
    "india_ancient_medieval_india":   "古代インド（マウリヤ・グプタ朝）",
    "india_mughal_colonial":          "ムガル帝国・植民地時代",
    "southeast_asia_ancient":         "東南アジア古代王国",
    "southeast_asia_colonial":        "東南アジア植民地時代",
    "southeast_asia_independence":    "東南アジア独立運動",
    "north_america_frontier":         "アメリカ西部開拓",
    "north_america_independence":     "アメリカ独立革命",
    "north_america_civil_war":        "南北戦争",
    "latin_america_sun_empire":       "古代メソアメリカ・アンデス文明",
    "latin_america_colonial_era":     "ラテンアメリカ植民地時代",
    "latin_america_liberation_era":   "ラテンアメリカ独立運動",
    "world_wars_ww1":                 "第一次世界大戦",
    "world_wars_interwar":            "戦間期（ファシズム台頭）",
    "world_wars_ww2_europe":          "第二次世界大戦（ヨーロッパ戦線）",
    "world_wars_ww2_pacific":         "第二次世界大戦（太平洋戦線）",
    "cold_war_cold_war_early":        "冷戦初期",
    "cold_war_cold_war_proxy":        "冷戦・代理戦争期",
    "cold_war_cold_war_end":          "冷戦終結",
};

// 地域・時代タグごとの第1位称号
export const TAG_TITLES = {
    "china_five_hu":               "⚔️ 単于",
    "china_ancient_china":         "👑 始皇帝",
    "china_medieval_china":        "👑 大ハーン",
    "china_early_modern_china":    "🐉 龍の玉座",
    "mideast_ancient_orient":      "🌙 ファラオ",
    "mideast_islamic_expansion":   "☪️ 正統カリフ",
    "mideast_turco_mongol":        "☪️ スルタン・ハン",
    "mideast_modern_turkey":       "🌙 アタテュルク",
    "africa_african_kingdoms":     "👑 ムサ王",
    "africa_scramble_for_africa":  "⚔️ マフディー",
    "europe_napoleon":             "🦅 コルシカの鷲",
    "europe_age_of_exploration":   "⚓ 航海王子",
    "europe_russia":               "👑 ツァーリ",
    "europe_britain":              "🩸 血の女王",
    "europe_germanic":             "👑 フランク王",
    "europe_ancient":              "🏛️ インペラトル",
    "europe_medieval":             "🏛️ 教皇",
    "europe_modern":               "🏛️ 啓蒙専制君主",
    "india_indus":                 "🏺 インダスの民",
    "india_ancient_medieval_india":"🕉️ 転輪聖王",
    "india_mughal_colonial":       "🕉️ パードシャー",
    "southeast_asia_ancient":      "🌿 アンコールの覇者",
    "southeast_asia_colonial":     "🌺 香料諸島の王",
    "southeast_asia_independence": "🕊️ 独立の父",
    "north_america_frontier":      "🤠 開拓王",
    "north_america_independence":  "🦅 建国の父",
    "north_america_civil_war":     "⚔️ 将軍",
    "latin_america_sun_empire":    "☀️ 太陽の皇帝",
    "latin_america_colonial_era":  "⚜️ 総督閣下",
    "latin_america_liberation_era":"🦅 リベルタドール",
    "world_wars_ww1":              "✈️ 撃墜王",
    "world_wars_interwar":         "🔥 ファシスト",
    "world_wars_ww2_europe":       "⚡ 総統",
    "world_wars_ww2_pacific":      "☢️ マンハッタン",
    "cold_war_cold_war_early":     "☭ 赤と青の世界",
    "cold_war_cold_war_proxy":     "🔴 革命か自由か",
    "cold_war_cold_war_end":       "💰 市場の勝利"
};
